### GET request with a header
GET http://localhost:8081
Accept: application/json

### GET request with a header
GET http://localhost:8081
Content-Type: text/html

### GET request with parameter
GET http://localhost:8081/get?show_env=1
Accept: application/json

### GET request with environment variables
GET {{host}}/get?show_env={{show_env}}
Accept: application/json

### GET request with disabled redirects
# @no-redirect
GET http://httpbin.org/status/301

### GET request with dynamic variables
GET http://localhost:8081/
Content-Type: application/json

###


### Send POST request with json body
POST http://localhost:8081/?a=22&b=222
Content-Type: application/json

{
  "id": 999,
  "value": "2222content"
}

### Send POST request with body as parameters
POST http://localhost:8081/?a=22&b=222
Content-Type: application/x-www-form-urlencoded

id=999&value=content

### Send a form with the text and file fields
POST https://httpbin.org/post
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="element-name"
Content-Type: text/plain

Name
--WebAppBoundary
Content-Disposition: form-data; name="data"; filename="data.json"
Content-Type: application/json

< ./request-form-data.json
--WebAppBoundary--

### Send request with dynamic variables in request's body
POST https://httpbin.org/post
Content-Type: application/json

{
  "id": {{$uuid}},
  "price": {{$randomInt}},
  "ts": {{$timestamp}},
  "value": "content"
}

###