"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.HttpHeaders = void 0;
var HttpHeaders;
(function (HttpHeaders) {
    HttpHeaders["ContentLength"] = "Content-Length";
    HttpHeaders["ContentType"] = "Content-Type";
    HttpHeaders["Accept"] = "Accept";
    HttpHeaders["Authorization"] = "Authorization";
    HttpHeaders["CacheControl"] = "Cache-Control";
    HttpHeaders["Connection"] = "Connection";
    HttpHeaders["Date"] = "Date";
    HttpHeaders["Host"] = "Host";
    HttpHeaders["Pragma"] = "Pragma";
    HttpHeaders["Trailer"] = "Trailer";
    HttpHeaders["TransferEncoding"] = "Transfer-Encoding";
    HttpHeaders["Upgrade"] = "Upgrade";
    HttpHeaders["Via"] = "Via";
    HttpHeaders["Warning"] = "Warning";
    HttpHeaders["AcceptCharset"] = "Accept-Charset";
    HttpHeaders["AcceptEncoding"] = "Accept-Encoding";
    HttpHeaders["AcceptLanguage"] = "Accept-Language";
    HttpHeaders["Expect"] = "Expect";
    HttpHeaders["From"] = "From";
    HttpHeaders["MaxForwards"] = "Max-Forwards";
    HttpHeaders["Referer"] = "Referer";
    HttpHeaders["UserAgent"] = "User-Agent";
    HttpHeaders["Cookie"] = "Cookie";
    HttpHeaders["SetCookie"] = "Set-Cookie";
    HttpHeaders["Cookie2"] = "Cookie2";
    HttpHeaders["SetCookie2"] = "Set-Cookie2";
    HttpHeaders["Location"] = "Location";
    HttpHeaders["IfModifiedSince"] = "If-Modified-Since";
    HttpHeaders["IfUnmodifiedSince"] = "If-Unmodified-Since";
    HttpHeaders["IfMatch"] = "If-Match";
    HttpHeaders["IfNoneMatch"] = "If-None-Match";
    HttpHeaders["IfRange"] = "If-Range";
})(HttpHeaders = exports.HttpHeaders || (exports.HttpHeaders = {}));
//# sourceMappingURL=HttpHeaders.js.map