"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Mimes = void 0;
var Mimes;
(function (Mimes) {
    Mimes["ApplicationJson"] = "application/json";
    Mimes["ApplicationOctetStream"] = "application/octet-stream";
    Mimes["ApplicationXml"] = "application/xml";
    Mimes["ApplicationJsonPatch"] = "application/json-patch+json";
    Mimes["ApplicationXWwwFormUrlencoded"] = "application/x-www-form-urlencoded";
    Mimes["TextPlain"] = "text/plain";
    Mimes["TextHtml"] = "text/html";
    Mimes["All"] = "*/*";
    Mimes["TextCss"] = "text/css";
    Mimes["TextJavascript"] = "text/javascript";
    Mimes["TextXml"] = "text/xml";
    Mimes["TextXslt"] = "text/xslt";
    Mimes["TextXmlDtd"] = "text/xml-dtd";
    Mimes["TextPlainUtf8"] = "text/plain; charset=utf-8";
    Mimes["ImagePng"] = "image/png";
    Mimes["ImageGif"] = "image/gif";
    Mimes["ImageJpeg"] = "image/jpeg";
    Mimes["ImageSvg"] = "image/svg+xml";
    Mimes["ImageBmp"] = "image/bmp";
    Mimes["ImageTiff"] = "image/tiff";
    Mimes["ImagePdf"] = "application/pdf";
    Mimes["ImageXBmp"] = "image/x-bmp";
    Mimes["ImageXpixmap"] = "image/x-xpixmap";
    Mimes["ImageXxbm"] = "image/x-xbm";
    Mimes["MultipartFormData"] = "multipart/form-data";
})(Mimes = exports.Mimes || (exports.Mimes = {}));
//# sourceMappingURL=Mimes.js.map